import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { cookieToInitialState } from "wagmi";
import Web3ModalProvider from "@/context/wagmi";
import { headers } from "next/headers";
import { Toaster } from "sonner";
import { wagmiAdapter } from "@/config/wagmi";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ABC launcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiAdapter.wagmiConfig,
    headers().get("cookie")
  );
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={nunito.className}>
        <div className="min-h-screen flex flex-col relative overflow-x-hidden">
          <Toaster />
          <Web3ModalProvider initialState={initialState}>
            <Header />
            <div className="flex-1 flex items-center">{children}</div>
          </Web3ModalProvider>
        </div>
      </body>
    </html>
  );
}
